service: serverless-name-generator
provider:
  name: aws
  runtime: nodejs6.10
plugins:
  - serverless-offline
functions:
  generate:
    handler: handler.handler # required, handler set in AWS Lambda
    events:
      - http:
          path: generate
          method: get